image: atlassian/default-image:latest

pipelines:
  branches:
    development:
      - step:
          name: Deploy to Server
          caches:
            - custom-docker-cache
          script:
            - echo "Deploying to server..."
            - pipe: atlassian/ssh-run:0.8.0
              variables:
                SSH_USER: $SERVER_USER
                SERVER: $SERVER_IP
                COMMAND: |
                  cd /root/client-portal-fe
                  pwd
                  cd client-portal
                  docker-compose -f "docker-compose.yml" up -d --build

definitions:
  caches:
    custom-docker-cache: /var/lib/docker