image: atlassian/default-image:latest

pipelines:
  branches:
    development:
      - step:
          name: Deploy to Server
          caches:
            - custom-docker-cache
          script:
            - echo "Deploying to production server..."
            - pipe: atlassian/ssh-run:0.8.0
              variables:
                SSH_USER: $PROD_SERVER_USER
                SERVER: $PROD_SERVER_IP
                COMMAND: |
                  cd /usr/share/nginx/tradx/client-portal-fe/
                  git checkout development && git pull
                  cd client-portal/
                  docker compose -f docker-compose.prod.yaml up --build -d
    development:
      - step:
          name: Deploy to Server
          caches:
            - custom-docker-cache
          script:
            - echo "Deploying to development server..."
            - pipe: atlassian/ssh-run:0.8.0
              variables:
                SSH_USER: $DEV_SERVER_USER
                SERVER: $DEV_SERVER_IP
                COMMAND: |
                  cd /usr/share/nginx/tradx/client-portal-fe/
                  git checkout development && git pull
                  cd client-portal/
                  docker compose -f docker-compose.prod.yaml up --build -d

definitions:
  caches:
    custom-docker-cache: /var/lib/docker