export type CurrentDrawerType =
  | "trades"
  | "market"
  | "events"
  | "help"
  | "assets"
  | null;

export type LeftSubDrawer =
  | "help-center"
  | "support"
  | "trading-platform"
  | "what-is-trading"
  | "why-coose-us"
  | null;

  export type RightDrawerContent =
    | "account"
    | "payments"
    | "profile"
    | "verification"
    | "verify-payment"
    | null;

  export type RightSubDrawerContent =
    | "settings"
    | "twofactor"
    | "personalSettings"
    | "verification"
    | "appearance"
    | "transfer"
    | "trading"
    | "notifications"
    | "barcode"
    | "user-notifications"
    | "change-password"
    | "edit-name"
    | "confirm-email"
    | "confirm-phone"
    | "select-account"
    | "withdraw"
    | "add-account"
    | "traders-way"
    | "invite-friends"
    | "verify-payment"
    | "mega-box-rewards"
    | "payments-deposit"
    | "select-deposit-amount"
    | "payment-method"
    | "card-details-menu"
    | "payments-promo-code"
    | "select-withdraw-account"
    | "boost-cubes"
    | "referral-program"
    | "depoist-successful"
    | "transfer-successful"
    | "promo-code-applied"
    | "verification-helpcenter-menu"
    | "get-rewards-deposit"
    | "add-account-name"
    | "verification-helpcenter-sub-menu"
    | "password-success"
    | null;