import { Form, Input } from 'antd'
import React, { useState } from 'react'
// import FormInput from '../components/FormInput'
import { SubmitHandler, useForm } from 'react-hook-form';
import './settingsProfile.scss'
import DropDownOptions from '../components/dropDownOptions/DropDown';
import ChangePassword from '../../changePassword/ChangePassword';
import { Editable } from 'assets/icons';
import FormInput from '../components/FormInput';
// import FormInput from 'pages/private/platform/kyc/components/FormInput';
interface formDataProps{
    first_name: string;
    last_name: string;
    email: string
}

const Settings = () => {
    const [formData, setFormData] = useState<formDataProps>({
        first_name: "",
        last_name: "",
        email: ""
    })
    const [form] = Form.useForm()

    const handleInputChange = () => {

    }
    const { handleSubmit, register, reset, setValue, formState: { errors } } = useForm<formDataProps>();


    const onSubmit: SubmitHandler<formDataProps> = () => {

       
      };
  return (
    <div className='settingProfile h-full bg-[#1F324D66] p-8 rounded-lg overflow-y-auto'>
        <h3 className='text-xl text-white '>Personal Information</h3>

        <div className=''>
            <div className="form-container mb-10">

             <Form form={form} layout="vertical">
              <div className='flex flex-col  gap-2'>

                <div className='form-tool bg--200 relative'>                    
                    <span className='absolute top-1/2 -translate-y-1/2 right-6 cursor-pointer'>
                    <Editable/>

                    </span>
                    <span className='absolute top-1.5 left-3 text-gray-100/70'>First name</span>

                    <FormInput inputValue="user" />
                

                </div>

                <div className='form-tool bg--200 relative'>                    
                    <span className='absolute top-1/2 -translate-y-1/2 right-6 cursor-pointer'>
                    <Editable/>

                    </span>
                    <span className='absolute top-1.5 left-3 text-gray-100/70'>Last name</span>

                    <FormInput inputValue="user"/>
                

                </div>

                <div className='form-tool bg--200 relative'>                    
                    <span className='absolute top-1/2 -translate-y-1/2 right-6 cursor-pointer'>
                    <Editable/>

                    </span>
                    <span className='absolute top-1.5 left-3 text-gray-100/70'>email</span>

                    <FormInput  inputValue="user"/>
                

                </div>

              </div>
        

           
            </Form>

            </div>


          


        <DropDownOptions 
            options='2 factor Authentication'>
            <div>
                <p>Use one-time passwords generated by an external app to log in. This will help protect your account from hackers.</p>
            </div>

            </DropDownOptions>

            <DropDownOptions 
            options='Password'>
            <div>
            <ChangePassword />
            </div>

            </DropDownOptions>

            <DropDownOptions 
            options='Notification'>
                <div>
                    <h2>   Notification Settings</h2>
                    <p>
                    Select the notifications you want to receive
                    </p>
                 </div> 

            </DropDownOptions>


        
    </div>
    </div>
  )
}

export default Settings